version: '3'

services:
  postgres:
    image: postgres:12
    networks:
      - network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  network:
    driver: bridge